

USE ContosoRetailDW

SELECT
	DATEADD(DAY, 15, GETDATE()) AS DATE_ADD,
	DATEADD(DAY, -15, GETDATE()) AS DATE_ADD_MINUS,
	GETDATE() AS TODAY,
	DATEADD(HOUR, 2, GETDATE()) AS TWO_HOURS
--CTRL + SPACEBAR SHOWS THE AVAILABLE OPTIONS