

DECLARE @STRING VARCHAR(30);
SET @STRING = 'We are made of starstuff'

DECLARE @PARTOFSTRING VARCHAR(30);
SET @PARTOFSTRING = SUBSTRING(@STRING, 16, 24)

SELECT
	LEN(@STRING),
	LEN(@PARTOFSTRING),
	LEFT(@PARTOFSTRING, 4),
	RIGHT(@PARTOFSTRING, 5),
	CHARINDEX('starstuff', @STRING)