

USE PRIMEIRO_BD

UPDATE CLIENTES
SET EMAIL = 'PEVIOLINO@GMAIL.COM'
WHERE ID_CLIENTE = 1

UPDATE CLIENTES
SET 
	NOME = 'PEDRO CAIQUE 2',
	EMAIL = 'PEDROB2BUSINESS@GMAIL.COM'
WHERE 
	ID_CLIENTE = 2

SELECT * FROM CLIENTES